### ISSUE TITLE
Multiple Choice Grid Questions

### ISSUE THREAD

**Issue by TheABCDario** [mouryaabhay/Google-Form-Response-To-Discord#1]
Is there a way to have the code include the row names when posting answers to multiple choice grid questions?

**Comment by mouryaabhay** [comment]
> Is there a way to have the code include the row names when posting answers to multiple choice grid questions?


Do you mean by multiple choice questions? 

For multiple choice questions the script sends all the selected option in the embed. And if you want to customise the multiple choice questions output, you can do it.

**Comment by TheABCDario** [comment]
No, specifically I’m referring to grid style questions.  There is a type of question you can create on a Google form that is set up as a grid with columns and rows.  They have a multiple choice version, as well as a check box version and a scale version if you look at it.  When I run that type of question format through the current code, it gives me all the answers based off of the columns, but without text in the row I lose the context of what the answers are for.

**Comment by TheABCDario** [comment]
I’ll see if I can get some screenshots of an example here in a while.

**Comment by mouryaabhay** [comment]
> No, specifically I’m referring to grid style questions.  There is a type of question you can create on a Google form that is set up as a grid with columns and rows.  They have a multiple choice version, as well as a check box version and a scale version if you look at it.  When I run that type of question format through the current code, it gives me all the answers based off of the columns, but without text in the row I lose the context of what the answers are for.


I didn't considered that type of answer as it was difficult to format the output in discord embed. It might be possible to code that into the script but will not be possible to format it as one would want in discord embed.

**Comment by TheABCDario** [comment]
Ah, so for now the best solution would be to separate the grid question into individual questions so as to maintain the context of what’s being asked?

**Comment by TheABCDario** [comment]
The formatting I think would be fine though, just with the addition of the text in the grid rows in the answer boxes, if that’s makes sense.  For now though, as I’m not much for coding, the above idea of splitting the grid into separate questions is probably what I’ll need to do.  Thank you for your quick responses as well, it is appreciated.

**Comment by mouryaabhay** [comment]
> The formatting I think would be fine though, just with the addition of the text in the grid rows in the answer boxes, if that’s makes sense.  For now though, as I’m not much for coding, the above idea of splitting the grid into separate questions is probably what I’ll need to do.  Thank you for your quick responses as well, it is appreciated.


Understood. Adding text to the grid rows is definitely something we can explore. I'll prioritize this for a future update when discord adds such format for embeds.

In the meantime, I'm glad splitting the grid into separate questions is a workable solution for you. Please let me know if you encounter any issues with that approach.

Thanks again for your feedback and patience!
